//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
        }
    
        public int CustomerID { get; set; }
        public string ContactName { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public Nullable<int> StateID { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Phone { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
